CREATE DATABASE IF NOT EXISTS indicators;
USE indicators;

CREATE TABLE IF NOT EXISTS graphs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    file_path VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS graph_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    graph_id INT NOT NULL,
    data_json JSON NOT NULL,
    FOREIGN KEY (graph_id) REFERENCES graphs(id) ON DELETE CASCADE
);

INSERT IGNORE INTO graphs (type, title) VALUES
('perdas', 'MONITORAR OS TIPOS DE PERDAS NA PRODUÇÃO'),
('pcp', 'ENTREGAR A PRODUÇÃO NO PRAZO PLANEJADO'),
('qualidade', 'PRODUTO REPROCESSADO + REFUGO < 2% TOTAL'),
('manutencao', 'CUMPRIR O PLANO DE MANUTENÇÃO');
